name: Postman Collection Workflow

on:
  push:
    branches: [main]
  workflow_dispatch:
  schedule:
    - cron: "00 15 * * *"
    - cron: "00 02 * * *"
    - cron: "00 18 * * 1-5"

jobs:
  run-postman-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the code
        uses: actions/checkout@v4

      - name: Install Node.js and Newman
        run: |
          npm install -g newman newman-reporter-htmlextra

      - name: Run Postman Collection
        run: |
          newman run 'Inwarranty-flow Collection With CSV File.postman_collection.json' \
            -e QA.postman_environment.json \
            -d testdata.csv \
            -r cli,htmlextra \
            --reporter-htmlextra-export ./newman/index.html

      - name: Upload Full Newman Report as Artifact
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: Newman Full Report
          path: newman/*.html

      - name: Deploy Report to GitHub Pages
        if: always()
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: newman/
