name: Postman Collection Workflow

on:
  push:
    branches: [main]
  workflow_dispatch:
  schedule:
    - cron: "00 15 * * *"
    - cron: "00 02 * * *"
    - cron: "00 18 * * 1-5"

jobs:
  run-postman-test:
    runs-on: ec2-github-runner

    steps:
      - name: Checkout the code
        uses: actions/checkout@v4

      - name: Install Node.js and Newman
        run: |
          npm install -g newman newman-reporter-html

      - name: Run Postman Collection
        run: |
          newman run 'Inwarranty-flow Collection With CSV File.postman_collection.json' \
            -e QA.postman_environment.json \
            -d testdata.csv \
            -r cli,html \
            --reporter-html-export ./newman/index.html

      - name: Upload Full Newman Report as Artifact
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: Newman Full Report
          path: newman/*.html

      - name: Deploy Report to GitHub Pages
        if: always()
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: newman/


      - name: Send Email Notification
        if: always()
        uses: dawidd6/action-send-mail@v6
        with:
          server_address: smtp.gmail.com
          server_port: 465
          username: ${{ secrets.EMAIL_USERNAME }}
          password: ${{ secrets.EMAIL_PASSWORD }}
          subject: Pheonix InWarranty Flow Test Ececution
          to: davinderraju@gmail.com
          from: ${{ secrets.EMAIL_USERNAME }}
          body: |
                Hi,
                Phoenix Inwarranty flow has been succesfuluy exected. The report has been published and the URL is: https://idavinde.github.io/Phoenix-Inwarranty-Flow/
                
